name: payment-service
services:
  - name: payment-service
    source_dir: .
    build_command: mvn -B -DskipTests clean package
    run_command: java -jar target/payment-service-0.0.1-SNAPSHOT.jar
    envs:
      - key: SPRING_DATASOURCE_URL
        scope: RUN_TIME
      - key: SPRING_DATASOURCE_USERNAME
        scope: RUN_TIME
      - key: SPRING_DATASOURCE_PASSWORD
        scope: RUN_TIME
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
        scope: RUN_TIME
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SQUARE_API_TOKEN
        scope: RUN_TIME
      - key: SQUARE_LOCATION_ID
        scope: RUN_TIME
      - key: SQUARE_APPLICATION_ID
        scope: RUN_TIME
      - key: SQUARE_WEBHOOK_SIGNATURE_KEY
        scope: RUN_TIME
      - key: APP_ADMIN_USER
        scope: RUN_TIME
        value: admin
      - key: APP_ADMIN_PASS
        scope: RUN_TIME
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /actuator/health
